package vista;

import javax.swing.JOptionPane;

import abstractFactory.AbstractFactoryCRUD;
import abstractFactory.FabricaPaciente;
import crud.Create;

public class VentanaIngresoPaciente extends javax.swing.JFrame {

	/**
	 * Creates new form NewJFrame
	 */
	public VentanaIngresoPaciente() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		tipo_documento = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		numero_documento = new javax.swing.JTextField();
		categoria = new javax.swing.JTextField();
		nombre = new javax.swing.JTextField();
		apellido = new javax.swing.JTextField();
		tipo = new javax.swing.JTextField();
		fecha_nacimiento = new javax.swing.JTextField();
		telefono = new javax.swing.JTextField();
		correo = new javax.swing.JTextField();
		sexo = new javax.swing.JTextField();
		tipo_documento_afiliado = new javax.swing.JTextField();
		numero_documento_afiliado = new javax.swing.JTextField();
		crear = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		jLabel1.setText("REGISTRO DE PACIENTE");

		jLabel2.setText("Tipo de documento");

		tipo_documento.setToolTipText("");
		tipo_documento.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				tipo_documentoActionPerformed(evt);
			}
		});

		jLabel3.setText("Número de documento");

		jLabel4.setText("Categoria");

		jLabel6.setText("Nombre");

		jLabel7.setText("Apellido");

		jLabel8.setText("Tipo de afiliación");

		jLabel9.setText("Fecha de nacimiento");

		jLabel10.setText("Telefono");

		jLabel11.setText("Correo");

		jLabel12.setText("Sexo");

		jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		jLabel5.setText("Datos del Afiliado (Llenar solo en caso de ser beneficiario)");

		jLabel13.setText("Numero de documento");

		jLabel14.setText("Tipo de documento");

		apellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);

		numero_documento_afiliado.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				numero_documento_afiliadoActionPerformed(evt);
			}
		});

		crear.setText("Registrar");
		crear.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				crearActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(46, 46, 46)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel13)
												.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 368,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel12).addComponent(jLabel11).addComponent(
														jLabel10)
												.addComponent(jLabel9).addComponent(jLabel8).addComponent(jLabel7)
												.addComponent(jLabel6).addComponent(jLabel4))
										.addGap(0, 24, Short.MAX_VALUE))
								.addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(layout.createSequentialGroup().addGroup(
												layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel3).addComponent(jLabel2))
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(tipo_documento,
																javax.swing.GroupLayout.DEFAULT_SIZE, 161,
																Short.MAX_VALUE)
														.addComponent(numero_documento)))
										.addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 161,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE,
																161, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE,
																161, javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(fecha_nacimiento,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE, 161,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(tipo, javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE, 161,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																telefono, javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE, 161,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(correo,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE, 161,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(sexo, javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE, 161,
																javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addGap(32, 32, 32))
								.addGroup(layout
										.createSequentialGroup().addComponent(jLabel14)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addComponent(numero_documento_afiliado,
														javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
												.addComponent(tipo_documento_afiliado))
										.addGap(34, 34, 34))))
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(153, 153, 153).addComponent(crear))
								.addGroup(layout.createSequentialGroup().addGap(146, 146, 146).addComponent(jLabel1)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap().addComponent(jLabel1)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
						.addComponent(tipo_documento, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3)
						.addComponent(numero_documento, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4)
						.addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel6)
						.addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel7)
						.addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel8)
						.addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel9)
						.addComponent(fecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel10)
						.addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel11)
						.addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel12)
						.addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel14)
						.addComponent(tipo_documento_afiliado, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel13)
						.addComponent(numero_documento_afiliado, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18).addComponent(crear).addContainerGap(36, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void tipo_documentoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tipo_documentoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_tipo_documentoActionPerformed

	private void crearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_crearActionPerformed
		// TODO add your handling code here:

		
		
		AbstractFactoryCRUD miFabrica;
		Create create;
		miFabrica = new FabricaPaciente(Integer.parseInt(numero_documento.getText()), 
				tipo_documento.getText(), 
				Integer.parseInt(categoria.getText()), 
				nombre.getText(), apellido.getText(), 
				tipo.getText(), 
				fecha_nacimiento.getText(),
				Long.parseLong(telefono.getText()), 
				correo.getText(), 
				sexo.getText(),
				tipo_documento_afiliado.getText(),
				Integer.parseInt( numero_documento_afiliado.getText())
				);
		create = miFabrica.crearRegistro();
		create.operacionCrud();
		
		String test = Integer.parseInt(numero_documento.getText())+"\n"+ 
				tipo_documento.getText()+ "\n"+
				Integer.parseInt(categoria.getText())+ "\n"+
				nombre.getText()+"\n"+ apellido.getText()+ "\n"+
				tipo.getText()+"\n"+
				fecha_nacimiento.getText()+"\n"+
				Long.parseLong(telefono.getText())+ "\n"+
				correo.getText()+"\n"+
				sexo.getText()+"\n"+
				tipo_documento_afiliado.getText()+"\n"+
				Integer.parseInt( numero_documento_afiliado.getText());
		
		System.out.println(test);
		
		System.out.println("Si llego hasta acá");
//		read = miFabrica.readRegistro();
//		ArrayList<Object> arrTemp = read.operacionCrud();
//		System.out.println("Codigo"+arrTemp.get(0)+"\n Nombre: "+ arrTemp.get(1)+"\nApellido " +arrTemp.get(2)+"\n Tipo de afiliacion: "+arrTemp.get(3));
//		System.out.println("Holaaa mundo");
	}// GEN-LAST:event_crearActionPerformed

	private void numero_documento_afiliadoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_numero_documento_afiliadoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_numero_documento_afiliadoActionPerformed

	/**
	 * @param args the command line arguments
	 */
	/*
	 * public static void main(String args[]) { Set the Nimbus look and feel
	 * //<editor-fold defaultstate="collapsed"
	 * desc=" Look and feel setting code (optional) "> If Nimbus (introduced in Java
	 * SE 6) is not available, stay with the default look and feel. For details see
	 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 * 
	 * try { for (javax.swing.UIManager.LookAndFeelInfo info :
	 * javax.swing.UIManager.getInstalledLookAndFeels()) { if
	 * ("Nimbus".equals(info.getName())) {
	 * javax.swing.UIManager.setLookAndFeel(info.getClassName()); break; } } } catch
	 * (ClassNotFoundException ex) {
	 * java.util.logging.Logger.getLogger(VentanaIngresoPaciente.class.getName()).
	 * log(java.util.logging.Level.SEVERE, null, ex); } catch
	 * (InstantiationException ex) {
	 * java.util.logging.Logger.getLogger(VentanaIngresoPaciente.class.getName()).
	 * log(java.util.logging.Level.SEVERE, null, ex); } catch
	 * (IllegalAccessException ex) {
	 * java.util.logging.Logger.getLogger(VentanaIngresoPaciente.class.getName()).
	 * log(java.util.logging.Level.SEVERE, null, ex); } catch
	 * (javax.swing.UnsupportedLookAndFeelException ex) {
	 * java.util.logging.Logger.getLogger(VentanaIngresoPaciente.class.getName()).
	 * log(java.util.logging.Level.SEVERE, null, ex); } //</editor-fold>
	 * 
	 * Create and display the form java.awt.EventQueue.invokeLater(new Runnable() {
	 * public void run() { new VentanaIngresoPaciente().setVisible(true); } }); }
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextField apellido;
	private javax.swing.JTextField categoria;
	private javax.swing.JTextField correo;
	private javax.swing.JButton crear;
	private javax.swing.JTextField fecha_nacimiento;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JTextField nombre;
	private javax.swing.JTextField numero_documento;
	private javax.swing.JTextField numero_documento_afiliado;
	private javax.swing.JTextField sexo;
	private javax.swing.JTextField telefono;
	private javax.swing.JTextField tipo;
	private javax.swing.JTextField tipo_documento;
	private javax.swing.JTextField tipo_documento_afiliado;
	// End of variables declaration//GEN-END:variables
}
